### PR TITLE
FEATURE(repository): Add RHEL7 managment

### PR DESCRIPTION
**Pull request by cdelgehier**
##### ISSUE TYPE
- Feature

 ##### SUMMARY
RHEL7 is similar to Centos7 but not entirely

 ##### SCOPE (skeleton only)
- SDS
- OIOFS
- OIOFS_HA

 ##### IMPACT
N/A

 ##### ADDITIONAL INFORMATION

### CODE REVIEW

**Comment by vincent-legoll** [comment]
I think this requires a RHEL7 CI

**Comment by vdombrovski** [comment]
Do we really want to dupe repo setup code on RHEL distros? LGTM otherwise.

**Comment by cdelgehier** [comment]
@vincent-legoll how ? There is no rhel container

**Comment by vincent-legoll** [comment]
I've created a Jira to track adding CI
https://github.com/open-io/ansible-role-openio-repository/pull/43
so that we can merge this now...

**Pull request merged**
